export const NAV_GROUPS = [
  {
    label: "Inbox",
    items: [
      { key: "messages", label: "Messages", icon: "ti-message-circle", color: "#3b82f6" },
      { key: "chats", label: "AI Chats", icon: "ti-messages", color: "#8b5cf6" },
    ]
  },
  {
    label: "Content",
    items: [
      { key: "projects", label: "Projects", icon: "ti-briefcase", color: "#10b981" },
      { key: "blog", label: "Blog & Articles", icon: "ti-pencil", color: "#06b6d4" },
      { key: "testimonials", label: "Testimonials", icon: "ti-quote", color: "#8b5cf6" },
      { key: "updates", label: "Updates", icon: "ti-bolt", color: "#f59e0b" },
      { key: "skills", label: "Skills", icon: "ti-star", color: "#06b6d4" },
      { key: "experience", label: "Experience", icon: "ti-id-badge", color: "#6366f1" },
      { key: "education", label: "Education", icon: "ti-book", color: "#ec4899" },
      { key: "certifications", label: "Certifications", icon: "ti-certificate", color: "#f97316" },
    ]
  },
  {
    label: "Intelligence",
    items: [
      { key: "analytics", label: "Analytics Hub", icon: "ti-chart-bar", color: "#3b82f6" },
      { key: "copilot", label: "AI Copilot & ATS", icon: "ti-sparkles", color: "#8b5cf6" },
      { key: "assets", label: "Asset Storage", icon: "ti-folder", color: "#10b981" },
    ]
  },
  {
    label: "System",
    items: [
      { key: "theme", label: "Theme Studio", icon: "ti-palette", color: "#ec4899" },
      { key: "settings", label: "Settings", icon: "ti-settings", color: "#6b7280" },
      { key: "backup", label: "Backup & Restore", icon: "ti-database", color: "#f59e0b" },
      { key: "audit", label: "Audit & Health", icon: "ti-activity", color: "#ef4444" },
    ]
  },
];

export const ALL_NAV_ITEMS = NAV_GROUPS.flatMap(g => g.items);

export const SKILL_CATEGORIES = [
  'languages',
  'frameworks',
  'developer_tools',
  'libraries_ml',
  'cloud_databases',
  'other'
];

export const SKILL_LEVELS = [
  'Beginner',
  'Intermediate',
  'Advanced',
  'Expert',
  'Master'
];

export const styles = {
  btn: {
    padding: '8px 16px',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: 500,
    cursor: 'pointer',
    border: '1px solid var(--border-color)',
    background: 'var(--bg-secondary)',
    color: 'var(--text-primary)',
    transition: 'all 0.2s ease',
  },
  btnPrimary: {
    padding: '8px 16px',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: 500,
    cursor: 'pointer',
    border: 'none',
    background: '#3b82f6',
    color: '#ffffff',
    transition: 'all 0.2s ease',
    boxShadow: '0 4px 12px rgba(59, 130, 246, 0.25)',
  },
  shell: {
    display: "grid",
    gridTemplateColumns: "220px 1fr",
    gridTemplateRows: "1fr",
    position: "fixed",
    inset: 0,
    background: "var(--bg-primary)",
    fontFamily: "system-ui, -apple-system, sans-serif"
  },
  sidebar: {
    background: "var(--sidebar-bg)",
    borderRight: "1px solid var(--border-color)",
    padding: "24px 12px",
    boxSizing: "border-box"
  },
  sidebarLabel: {
    fontSize: 11,
    color: "var(--text-muted)",
    letterSpacing: 0.5,
    fontWeight: 500,
    margin: "0 0 12px",
    padding: "0 10px",
  },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 10px",
    borderRadius: "8px",
    fontSize: 13,
    border: "none",
    cursor: "pointer",
    textAlign: "left",
    transition: "all 0.15s ease",
    position: "relative"
  },
  navBadge: {
    marginLeft: "auto",
    background: "#ef4444",
    color: "white",
    fontSize: 10,
    fontWeight: 700,
    borderRadius: "10px",
    padding: "1px 7px",
  },
  main: {
    padding: "24px",
    display: "flex",
    flexDirection: "column",
    overflowY: "auto",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    borderBottom: "1px solid var(--border-color)",
    paddingBottom: "16px",
    marginBottom: "24px"
  },
  headerLabel: {
    fontSize: 12,
    color: "var(--text-muted)",
    margin: "0 0 4px"
  },
  headerEmail: {
    fontSize: 14,
    color: "var(--text-primary)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "var(--bg-primary)",
  },
  topBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 28px",
    borderBottom: "1px solid var(--border-color)",
    background: "var(--sidebar-bg)",
    flexShrink: 0,
    gap: 16,
  },
  topBarTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: "var(--text-primary)",
    margin: 0,
    letterSpacing: "-0.3px",
  },
  topBarSub: {
    fontSize: 11,
    color: "var(--text-muted)",
    margin: "2px 0 0",
  },
  iconAction: {
    width: 32,
    height: 32,
    borderRadius: 8,
    background: "var(--bg-primary)",
    border: "1px solid var(--border-color)",
    color: "var(--text-primary)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "all 0.15s",
    flexShrink: 0,
  },
  body: {
    flex: 1,
    overflowY: "auto",
    padding: "24px 28px",
  },
  statsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "16px",
    marginBottom: "24px",
  },
  statCard: {
    background: "var(--bg-secondary, var(--bg-light))",
    border: "1px solid var(--border-color)",
    borderRadius: "14px",
    padding: "18px 20px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
    transition: "box-shadow 0.2s",
  },
  statLabel: {
    fontSize: 11,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    color: "var(--text-muted)",
    margin: "0",
  },
  statValue: {
    fontSize: 28,
    fontWeight: 800,
    margin: "4px 0 0",
    letterSpacing: "-1px",
    lineHeight: 1.1,
    display: "flex",
    alignItems: "center",
  },
  panelContainer: {
    flex: 1,
  },
  panelCard: {
    background: "var(--bg-secondary, var(--bg-light))",
    border: "1px solid var(--border-color)",
    borderRadius: "16px",
    overflow: "hidden",
    boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
  },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px 22px",
    borderBottom: "1px solid var(--border-color)",
    background: "var(--sidebar-bg)",
    gap: 12,
    flexWrap: "wrap",
  },
  panelTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "var(--text-primary)",
    margin: 0,
    letterSpacing: "-0.2px",
  },
  panelAction: {
    background: "var(--primary-blue)",
    color: "#fff",
    border: "none",
    fontSize: 12,
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    gap: 6,
    cursor: "pointer",
    padding: "6px 14px",
    borderRadius: "8px",
    whiteSpace: "nowrap",
    transition: "opacity 0.15s",
  },
  emptyState: {
    padding: "60px 20px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: "var(--text-primary)",
    margin: "16px 0 4px",
  },
  emptyDescription: {
    fontSize: 13,
    color: "var(--text-muted)",
    margin: 0,
    maxWidth: 300,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    textAlign: "left",
  },
  th: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    color: "var(--text-muted)",
    fontWeight: 700,
    padding: "11px 20px",
    borderBottom: "1px solid var(--border-color)",
    background: "var(--sidebar-bg)",
    whiteSpace: "nowrap",
  },
  td: {
    fontSize: 13,
    color: "var(--text-primary)",
    padding: "14px 20px",
    borderBottom: "1px solid var(--border-color)",
    verticalAlign: "middle",
  },
  badge: {
    padding: "3px 9px",
    borderRadius: "99px",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.2px",
  },
  iconBtn: {
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: 5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "6px",
    transition: "background 0.15s",
  },
  input: {
    width: "100%",
    padding: "9px 12px",
    borderRadius: "8px",
    border: "1px solid var(--border-color)",
    background: "var(--bg-primary)",
    color: "var(--text-primary)",
    fontSize: 13,
    boxSizing: "border-box",
    outline: "none",
    transition: "border-color 0.15s",
  },
  settingsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))",
    gap: 16,
  },
  settingGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  settingLabel: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.6px",
  },
};

export const MODAL_STYLES = {
  overlay: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, padding: 20 },
  content: { background: 'var(--bg-primary)', borderRadius: '16px', width: '100%', maxWidth: 700, maxHeight: '90vh', display: 'flex', flexDirection: 'column', boxShadow: '0 20px 40px rgba(0,0,0,0.2)', overflow: 'hidden' },
  header: { padding: '16px 24px', borderBottom: '1px solid var(--border-color)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: 'var(--sidebar-bg)', flexShrink: 0 },
  title: { margin: 0, fontSize: 16, fontWeight: 700, color: 'var(--text-primary)' },
  body: { padding: '24px', display: 'flex', flexDirection: 'column', gap: 18, overflowY: 'auto' },
  footer: { padding: '16px 24px', borderTop: '1px solid var(--border-color)', display: 'flex', justifyContent: 'flex-end', gap: 10, flexShrink: 0 },
  label: { fontSize: 12, fontWeight: 600, color: 'var(--text-muted)', letterSpacing: '0.5px', textTransform: 'uppercase', display: 'block', marginBottom: 6 },
  input: { width: "100%", padding: "9px 12px", borderRadius: "8px", border: "1px solid var(--border-color)", background: "var(--bg-primary)", color: "var(--text-primary)", fontSize: 13, boxSizing: "border-box", outline: "none", transition: "border-color 0.15s" },
  sectionLabel: { fontSize: 13, fontWeight: 600, color: 'var(--text-primary)', margin: 0 }
};
